# Generated by Django 5.0.1 on 2024-01-31 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_grouppost_alter_student_cat_student_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='group',
            field=models.ManyToManyField(blank=True, related_name='group_students', to='student.grouppost'),
        ),
    ]
